version: '3'

services:
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/home/app/web
    ports:
      - 1338:80
    depends_on:
      - web
    networks:
      - app


  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'vnv_project'
      MYSQL_USER: 'django'
      MYSQL_PASSWORD: 'django'
      MYSQL_ROOT_PASSWORD: "yura01"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - app

  web:
    build:
      dockerfile: ./docker/python/Dockerfile
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web
    ports:
      - '8000:8000'
    depends_on:
      - db
    links:
      - db
    networks:
      - app

networks:
  app:
    driver: bridge
